ecommercepro/cart/urls.py
from django.urls import path
from  . import views

app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
    path('confirm',views.confirm,name='confirm'),
]

ecommercepro/credentials/urls.py
from django.urls import path
from . import views

app_name='credentials'

urlpatterns = [
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

ecommercepro/ecommercepro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('',include('credentials.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommercepro/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

ecommercepro/shop/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
]

ecommercepro/cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommercepro/cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from  shop.models import Product
from .models import Cart,CartItem

# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart


def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
            )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

def confirm(request):
    return render(request,'confirm.html')

ecommercepro/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommercepro/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        This is the cart page. proceed to review your items place the order.
{% endblock %}
{% block title %}
    Cart - ABC Company PVT LTD
{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your Shopping Cart is empty
                </h1>
                <br>
                <p class="text-center">
                    Please Click <a href="{% url 'shop:allProdCat' %}">Here</a> to continue shopping.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your Shopping Cart
                </h1>
                <br>
            </div>
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th colspan="5">
                                    Your Items
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}
                                <tr>
                                    <td>
                                        <img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" width="100px" height="100px">
                                    </td>
                                    <td class="text-left">
                                        {{cart_item.product.name}}
                                        <br>
                                        SKU: {{cart_item.product.id}}
                                        <br>
                                        Price: $ {{cart_item.product.price}}
                                        <br>
                                        Qty: {{cart_item.quantity}} x $ {{cart_item}}
                                    </td>
                                    <td>
                                        {{cart_item.sub_total}}
                                    </td>
                                    {% if cart_item.quantity < cart_item.product.stock %}
                                        <td>
                                            <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                                            &nbsp<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                            &nbsp<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                                        </td>
                                    {% else %}
                                        <td>
                                            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th>
                                    CheckOut
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    Please review your cart items before proceeding with the order payment.
                                </td>
                            </tr>
                            <tr>
                                <td class="text-left">
                                    Your Total is : <strong> {{total}}</strong>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <a href="{% url 'cart:confirm' %}" class="btn btn-success btn-block my_custom_button">Place order</a>
                        <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock %}

ecommercepro/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to ABC Store where you can buys different items....
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}} - ABC Store
    {% else %}
        See Our New Collections - ABC Store
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row row_my_class">
            <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections</a> </p>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
    <div>
        <img src="{% static 'img/banner2.png' %}" alt="our products" width="100%" height="400px">
    </div>
    <br>
    <div>
        <h1>Our Products</h1>
        <p>Homemade chocolates are chocolates that are made from the home and not in a factory of some sort where mass production of chocolates is produced with a short period of time. Those who are into homemade chocolate retail businesses ensure that they target locations where they can easily attract children because children are the major consumers of products such as homemade chocolates and candies.</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx-auto">
            {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{product.get_url}}"><img class="card-image-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

ecommercepro/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Confirm Order</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:500px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
#select {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
#select{
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 125px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'cart:cart_detail' %}">
        {% csrf_token %}

        <center>
        <div class="container">
            <h1>Confirm Order</h1>
            <input type="text" name="name" placeholder= "Name" size="15" required /><br>
            <input type="text" name="address" placeholder="Address" required /><br>
            <input type="text" name="phone_no" placeholder="Phone Number" size="15"required /><br>
            <select name=”district” id="select">
                <option>District</option>
                <optgroup label="Kannur">
                    <option value=”Kambil”>Kambil</option>
                    <option value=”Payyannur”>Payyannur</option>
                    <option value=”Puthyatheru”>Puthyatheru</option>
                </optgroup>
                <optgroup label="Kochi">
                    <option value=”Mattachery”>Mattachery</option>
                    <option value=”Fort_Kochi”>Fort Kochi</option>
                    <option value=”Kodanad”>Kodanad</option>
                </optgroup>
                <optgroup label="Kozhikode">
                    <option value=”Mattachery”>Vadakara</option>
                    <option value=”Fort_Kochi”>Quilandy</option>
                    <option value=”Kodanad”>Beypore</option>
                </optgroup>
            </select><br>
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">Confirm</button><br><br>
            <h4><a href="{% url 'cart:cart_detail' %}" style="color:black;">Back</a></h4>
        </div>
        </center>
    </form>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body">
          <h2>Order placed</h2>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="myFunction()">OK</button>
        </div>
      </div>

    </div>
  </div>
<script type="text/javascript">
function myFunction() {
    window.location.href ={% url 'cart:cart_detail' %};
}
</script>

</body>
</html>

ecommercepro/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer" style="bottom:0;position:fixed;width:100%;left:0;right:0;">
    <p class="text-center">&copy; Chocolux online chocolate shopee.All Right Reserved</p>
</div>

ecommercepro/templates/header.html
{% load static %}

<header>
    <center>
        <a href="#"><img src="{% static 'img/logo1.png' %}" alt="logimage" width="130px" height="130px"></a>
    </center>
        <div class="topright">
            {% if user.is_authenticated %}
                {{user.username}}
                <a href="{% url 'credentials:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'credentials:register' %}">Register</a>
                <a href="{% url 'credentials:login' %}">Login</a>
            {% endif %}
        </div>
</header>

ecommercepro/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="Welcome to Chocolux where you can buys different items....">
    <title>See Our New Items - Chocolux</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
    </div>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                     </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#about">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#branches">Branch</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'credentials:login' %}">Shop Now</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    </div>
    <div class="container">
        <img src="{% static 'img/banner2.png' %}" alt="our products" width="100%" height="400px">
    </div><br>
    <div id="about" class="container">
        <h2>About</h2>
        <p>Homemade chocolates are chocolates that are made from the home and not in a factory of some sort where mass production of chocolates is produced with a short period of time. Those who are into homemade chocolate retail businesses ensure that they target locations where they can easily attract children because children are the major consumers of products such as homemade chocolates and candies.</p>
    </div><br>
    <div id="branches" class="container">
        <h2>Our Branches</h2>
        <div class="row">
            <div class="col-md-4">
                <b><p>Kannur</p></b>
                <p><i class='fas fa-location-arrow'></i>near caltex</p>
                <p><i class='fas fa-phone'></i>1234567</p>
                <p><i class='fas fa-envelope'></i>chocolux1@gmail.com</p>
            </div>
            <div class="col-md-4">
                <b><p>Calicut</p></b>
                <p><i class='fas fa-location-arrow'></i>near plasa</p>
                <p><i class='fas fa-phone'></i>1234567</p>
                <p><i class='fas fa-envelope'></i>chocolux1@gmail.com</p>
            </div>
            <div class="col-md-4">
                <b><p>Kochi</p></b>
                <p><i class='fas fa-location-arrow'></i>near smart city</p>
                <p><i class='fas fa-phone'></i>1234567</p>
                <p><i class='fas fa-envelope'></i>chocolux1@gmail.com</p>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommercepro/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 325px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'credentials:login' %}">
        {% csrf_token %}
        <center>
        <div class="container">
            <h1>Sign in</h1>
            <input type="text" name="username" placeholder= "Username" size="15" required /><br>
            <input type="password" name="password" placeholder="Password" size="15" required /><br>
            <input type="submit" class="registerbtn" value="Login"><br>
            {% for msg in messages %}
                <h4 style="color:red">{{msg}}</h4>
            {% endfor %}
            <p>Not Registered? please</p><a href="{% url 'credentials:register' %}"> Sign up</a>
            <p>Back to</p><a href="{% url 'credentials:home' %}">Home</a>

        </div>
        </center>
    </form>
</body>
</html>

ecommercepro/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
           <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
               <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"> <i class="fa fa-shopping-cart">{{item_count}}</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommercepro/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{product.name}} - ABC Store
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row my_prod_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>{{product.name}} </p>
        </div>
        <div class="container">
        <br>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <div style="min-width:18rem">
                        <img src="{{product.image.url}}" alt="{{product.name}}" width="200px" height="200px">
                     </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <div>
                        <h1 class="my_prod_title">{{product.name}}</h1>
                        <p>${{product.price}}</p>
                        <p class="my_title"> Product Description </p>
                        <p class="text-justify my_prod_text">{{product.description}}</p>
                        {% if product.stock <= 0 %}
                        <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                        {% else %}
                        <a class="btn-btn secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ecommercepro/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 125px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'credentials:register' %}">
        {% csrf_token %}

        <center>
        <div class="container">
            {% for msg in messages %}
                <h4 style="color:red">{{msg}}</h4>
            {% endfor %}
            <h1>Sign Up</h1>
            <input type="text" name="username" placeholder= "Username" size="15" required /><br>
            <input type="password" name="password" placeholder="Password" size="15" required /><br>
            <input type="password" name="cpassword" placeholder="Confirm Password" size="15"required /><br>
            <input type="reset" class="registerbtn" value="Reset">
            <input type="submit" class="registerbtn" value="Register"><br>
            <p>Already Registered? please</p><a href="{% url 'credentials:login' %}"> Sign in</a>
            <p>Back to</p><a href="{% url 'credentials:home' %}">Home</a>
        </div>
        </center>
    </form>
</body>
</html>

ecommercepro/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have variety of products.
{% endblock %}
{% block title %}
   Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
        <div class="row mx-auto">
            {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{product.get_url}}"><img class="card-image-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 result found</p>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}